Confluence/polarization
idia-astro/carta-python pull request #52
Opened 2022-09-14 01:14 UTC by confluence

Fixes #51. Any available polarization can be set (always by its numeric value). Keyword aliases are provided through a helper class. A list of available polarizations can be retrieved, and it can be queried by keyword. `polarizations` includes computed polarizations; `num_polarizations` does not.

Examples:

    from carta.constants import Polarization
    img.polarizations
    img.num_polarizations
    img.has_polarization(Polarization.Q)
    img.set_channel_polarization(polarization=Polarization.Q)
    img.set_channel_polarization(polarization=2)
    img.set_channel_polarization(polarization=Polarization.PANGLE)
    img.set_channel_polarization(polarization=17)

Future enhancement (in a separate issue): add a wrapper for return values (like `polarizations`) so that they are displayed as keywords rather than literals. For now the user will see the underlying integer values.

Possible future enhancement: set a (non-computed) polarization by index? Would this be useful?

2022-09-14 03:24 UTC, kswang1029 requested changes
when we do `print(img0.polarizations)` and see `[1, 2, 3, 4, 13, 14, 15, 16, 17]`, then if we do `print(img0.has_polarization(13))`, it is True returned. But if we do `print(img0.has_polarization(12))`, we will see

> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 624, in newfunc
>     param.validate(value, self)
>   File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 254, in validate
>     raise ValueError(f"{value} is not {self.description}")
> ValueError: 12 is not a class property of :obj:`carta.constants.Polarization`
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/kswang/carta_pythonInterface_testing/test.py", line 18, in <module>
>     print(img0.has_polarization(12))
>   File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 636, in newfunc
>     raise CartaValidationFailed(f"Invalid function parameter: {msg}")
> carta.util.CartaValidationFailed: Invalid function parameter: 12 is not a class property of carta.constants.Polarization

instead of a False.

2022-09-14 07:08 UTC, confluence commented
This is by design -- there is no polarization with value 12 (or 0, or 12345). So you can't check any of those, because they aren't valid polarizations. The input to the function is validated to disallow anything except a polarization value.

I could change this behaviour to allow any number to be checked, but I think that would be less correct (the purpose of validating the input is to prevent the user from entering an invalid integer value by mistake).

2022-09-14 07:12 UTC, kswang1029 commented
> This is by design -- there is no polarization with value 12 (or 0, or 12345). So you can't check any of those, because they aren't valid polarizations. The input to the function is validated to disallow anything except a polarization value.
> 
> I could change this behaviour to allow any number to be checked, but I think that would be less correct (the purpose of validating the input is to prevent the user from entering an invalid integer value by mistake).

I see. My concern here is `Image.has_polarization()` returns True or raises an exception. Not sure what application of this function would be? Maybe we don't need `Image.has_polarization()` at all as `Image.polarizations` can already tell users the available polarizations as a list. 🤔

2022-09-14 07:21 UTC, kswang1029 commented
> > This is by design -- there is no polarization with value 12 (or 0, or 12345). So you can't check any of those, because they aren't valid polarizations. The input to the function is validated to disallow anything except a polarization value.
> > I could change this behaviour to allow any number to be checked, but I think that would be less correct (the purpose of validating the input is to prevent the user from entering an invalid integer value by mistake).
> 
> I see. My concern here is `Image.has_polarization()` returns True or raises an exception. Not sure what application of this function would be? Maybe we don't need `Image.has_polarization()` at all as `Image.polarizations` can already tell users the available polarizations as a list. 🤔

@confluence never mind. I think we can keep `Image.has_polarization()` as using constants (eg Polarization.Q) as input is still useful.

2022-09-14 07:24 UTC, confluence commented
The main purpose is to allow the user to look up a polarization by keyword name. `polarizations` is a list of numbers. I added an issue (#53) for this -- I think it should be possible to create wrappers for this data so that the values are displayed as keywords (or possibly there's an existing enum-like feature in Python that I could use). If I put that in, it would mostly eliminate the need for functions like this.

2022-09-19 02:11 UTC, kswang1029 commented
For an image having 480 channels (index 0~479), if we do `img1.set_channel(480)`, we will see

carta.util.CartaValidationFailed: Invalid function parameter: 480 is greater than or equal to maximum value 480.

it should be 

carta.util.CartaValidationFailed: Invalid function parameter: 480 is greater than or equal to maximum value 479.

2022-09-19 07:32 UTC, confluence commented
Ah, good point. It should actually be "greater than maximum value of 480".

2022-09-19 07:42 UTC, confluence commented
The message is currently technically correct; it just isn't conveying the information that the upper bound may not be included. I'll start by changing minimum / maximum value to lower / upper bound, since the current phrasing implies that the bound is included. I have an idea for the rest.

2022-09-19 09:54 UTC, confluence commented
Upon reflection, I have also removed the `has_polarization` function, since the user can already use a keyword in exactly the same way to check whether `Polarization.I in img.polarizations` directly. I don't know what I was thinking before.

2022-09-20 02:11 UTC, kswang1029 commented
uh, it seems the revision breaks set_channel. In the following example, channel 20 is a valid one.

> img1.set_channel(20)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 630, in newfunc
    param.validate(value, self)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 574, in validate
    param.validate(value, parent)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 158, in validate
    raise ValueError(f"{value} is {cmp_str} upper bound {self.max}, but must be smaller.")
UnboundLocalError: local variable 'cmp_str' referenced before assignment

2022-09-20 07:12 UTC, confluence commented
Should be fixed now.

2022-09-21 06:13 UTC, kswang1029 approved these changes
this looks good now. 👍

2022-09-21 08:00 UTC, merged